name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Preflight
        run: make preflight

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: coverage
          retention-days: 7

      - name: Package Lambda
        run: |
          export NODE_ENV=dev
          npm run package
